---
title: " "
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'AboutMe.html'))})
output:
  html_document:
    df_print: paged
    css: "style.css"
---

<center> <h1>About me</h1> </center>

<div>
<div style="margin-bottom:20px;">
</div>

<center>
In my spare time, I run, together with other graduate students, [Community Based Project Evaluation (CBPE) group](https://cbpegroup.com/), a graduate student organization that has been providing voluntary statistical evaluation of programs administered by local nonprofits for over two years. Additionally, when I am not doing research, I teach dance.
 
<center>

</div>
<div style="margin-bottom:20px;">
</div>

<hr style="border:0.5px solid gray">

<center>
I have put together [resources here](https://docs.google.com/document/d/1aoryUTNnxxi_7e1q-mqYrkwfWZHiEQYqLbNbwZR1AAg/) on ways to help Ukrainian civilians if you are in the US.
<center>

<!-- Matomo -->
<script>
  var _paq = window._paq = window._paq || [];
  /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="https://amgithub.matomo.cloud/";
    _paq.push(['setTrackerUrl', u+'matomo.php']);
    _paq.push(['setSiteId', '1']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.async=true; g.src='//cdn.matomo.cloud/amgithub.matomo.cloud/matomo.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
<!-- End Matomo Code -->

