---
title: " "
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'CV.html'))})
output:
  html_document:
    df_print: paged
    css: "style.css"
---

</div>
<div style="margin-bottom:20px;">
</div>

</div>
<div style="margin-bottom:20px;">
</div>

### Education ###

##### _Doctor of Philosophy in Applied Economics & Management (Expected 2024)_ ##### 
Cornell University, Ithaca, NY 

##### _Master of Science in Applied Economics & Management (2020)_  #####  
Cornell University, Ithaca, NY 

##### _Bachelor of Arts in Mathematics & Economics (2014)_  #####
Mount Holyoke College, South Hadley, MA

### Research Interests ###

Public Economics & Applied Microeconomics; Economics & Indigenous peoples

### Special Committee ###

Dr. <a href="https://publicpolicy.cornell.edu/people/seth-sanders/" style="color: #8B0000; text-decoration: underline;">Seth Sanders</a> _(co-chair)_, Dr. <a href="https://www.kanbur.dyson.cornell.edu/" style="color: #8B0000; text-decoration: underline;">Ravi Kanbur</a> _(co-chair)_, Dr. 
<a href="https://dyson.cornell.edu/faculty-research/faculty/cmf257/" style="color: #8B0000; text-decoration: underline;">Chris Forman</a>, and Dr. <a href="https://harris.uchicago.edu/directory/dan-black" style="color: #8B0000; text-decoration: underline;">Dan Black</a> _(University of Chicago)_

### Selected Research in Progress ###

“Long-term effects of the WIC program and interaction effects of large-scale public programs”. 

"The effect of access to mental healthcare on teen and adolescent pregnancy".

“COVID-driven technology adoption and worker inequality in the US”, with <a href="https://scholar.google.com/citations?user=s7UfVc0AAAAJ&hl=en" style="color: #8B0000; text-decoration: underline;">Bledi Taska</a>.

 + Census Bureau Technical Note on constructing a crosswalk between private Lightcast (Burning Glass Technologies) job postings data and Census Bureau's restricted firm microdata, with <a href="https://www.philadelphiafed.org/our-people/bryan-stuart" style="color: #8B0000; text-decoration: underline;">Bryan Stuart</a>.
 
A study of the effects of education on mortality, with <a href="https://www.iza.org/people/affiliates/21739/ciprian-domnisoru" style="color: #8B0000; text-decoration: underline;">Ciprian Domnisoru</a> and <a href="https://eller.arizona.edu/people/evan-j-taylor" style="color: #8B0000; text-decoration: underline;">Evan Taylor</a>. 

“Native American tribal enrollment: What can be learned from over 20 years of data”, with Elijah Moreno.  

<a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3949116" style="color: #8B0000; text-decoration: underline;">"Understanding the Native American tribal disenrollment epidemic: An IV approach"</a>, with Elijah Moreno. 

"Destination categories, store choice, and beer distribution laws", with <a href="https://dyson.cornell.edu/faculty-research/faculty/bjr83/" style="color: #8B0000; text-decoration: underline;">Bradley Rickard</a> and <a href="https://search.asu.edu/profile/92424" style="color: #8B0000; text-decoration: underline;">Timothy Richards</a>. 

### Peer Reviewed Publications ###

<a href="https://www.sciencedirect.com/science/article/abs/pii/S0301421521001737" style="color: #8B0000; text-decoration: underline;">"Energy income and farm viability: Evidence from USDA farm survey data"</a>, with Travis Grout and Jennifer Ifft, Energy Policy, Volume 155, August 2021.

<a href="https://www.journals.uchicago.edu/doi/10.1093/reep/rey012" style="color: #8B0000; text-decoration: underline;">"Distribution of emissions allowances and the use of auction revenues in the European Union Emissions Trading System"</a>, with Åsa Löfgren, Dallas Burtraw, and Markus Wråke, Review of Environmental Economics and Policy 12(2), 2018.

### Other Publications ###

<a href="https://www.brookings.edu/wp-content/uploads/2016/08/hp-lit-review_final.pdf" style="color: #8B0000; text-decoration: underline;">"Measuring Productivity in Healthcare: An Analysis of the Literature"</a>, with <a href="https://www.brookings.edu/people/louise-sheiner/" style="color: #8B0000; text-decoration: underline;">Louise Sheiner</a>, Brookings Institution Working Paper, May 2016.

### Awards & Honors ###

<a href="https://equitablegrowth.org/people/anna-malinovskaya/" style="color: #8B0000; text-decoration: underline;">DC Center for Equitable Growth Doctoral Grant</a> ($15,000) for the project “Long-term own and dynamic complementarity effects of the WIC program” (2023)

<a href="https://www.russellsage.org/awarded-project/covid-driven-technology-adoption-and-worker-inequality-us" style="color: #8B0000; text-decoration: underline;">Russell Sage Foundation Dissertation Grant</a> ($10,000) for the project “COVID-driven technology adoption and worker inequality in the US” (2022)

<a href="https://teaching.cornell.edu/grants-awards/graduate-students-postdoctoral-fellows" style="color: #8B0000; text-decoration: underline;">Center for Teaching Innovation Graduate Teaching Fellowship</a> ($2,000), Cornell University (2022-2023)

<a href="https://dyson.cornell.edu/programs/graduate/awards/" style="color: #8B0000; text-decoration: underline;">Graduate Teaching Assistant – Outstanding Service Award 2021</a>, Dyson School of Applied Economics & Management, Cornell University (spring 2021)

Serve in Place Grant (for a community service project) from Cornell University (spring 2021)

### Research Experience ###

##### _Graduate Research Assistant to_ #####

Dr. Seth Sanders (Cornell University, spring 2022-)   

Dr. Bradley Rickard (Cornell University, summers 2020-2022) 

Dr. Ariel Ortiz-Bobea (Cornell University, spring 2020) 

Dr. Jennifer Ifft (Cornell University, fall 2019)

##### _Other Research Experience_ #####

<a href="https://www.brookings.edu/author/anna-malinovskaya/" style="color: #8B0000; text-decoration: underline;">Senior Research Assistant, Brookings Institution</a> (Hutchins Center on Fiscal & Monetary Policy), Washington DC (Jan. 2016 - July 2017)

<a href="https://www.rff.org/publications/working-papers/expected-versus-actual-outcomes-of-environmental-policies-the-clean-water-state-revolving-fund/" style="color: #8B0000; text-decoration: underline;">Research Assistant, Resources for the Future</a>, Washington DC (May 2014 - Dec. 2015)

### Selected Invited Presentations ###

Data Intensive Research Conference (2023) 

Knowledge Share Workshop, Social, Economic, and Housing Statistics Division [SEHSD] of the U.S. Census Bureau (2023) 

U.S. Census Bureau FSRDC Presentation Series (2023) 

Western Economic Association International (WEAI), 17th International Conference (2023) 

American Community Survey Data Users Conference, Population Reference Bureau (2023) 

Population Association of America (PAA) Annual Meeting (2021) 

Association for Public Policy Analysis and Management (APPAM) Annual Conference (2020)

### Service ###

Workshop Leader, <a href="https://www.eyh.cornell.edu/" style="color: #8B0000; text-decoration: underline;">Expanding Your Horizons Conference</a>, Cornell University, Ithaca, NY (April, 2023)

Volunteer, Community Investment Committee / T. Merrill Shipherd Committee Board, Tompkins County United Way, Ithaca, NY (January, 2020-)

Various Roles, Community-Based Project Evaluation Group (CBPE), Cornell University, Ithaca, NY (May, 2020-)

Certified Translator / Interpreter, Translator-Interpreter Program, Cornell University Public Service Center, Ithaca, NY (May, 2021-)

### Mentorship ###

Peer Mentor, Graduate Field of Applied Economics and Management Buddy Program, Cornell University, Ithaca, NY (2021-2023)

Mentee, the <a href="https://econmentoring.org/mentee-2022/" style="color: #8B0000; text-decoration: underline;">Association for Mentoring & Inclusion in Economics</a> (2022-2023)

### Software ###

Stata, SAS, R, Python, $\LaTeX$

### Other ###

Special Sworn Status preliminary approval (March, 2021 - )

Languages: English _(fluent)_, Russian _(fluent)_, Ukrainian _(heritage speaker)_

+ IELTS General Test, Overall Band Score: 9.0/9.0 (April, 2022)

</div>
<div style="margin-bottom:20px;">
</div>


<!-- Matomo -->
<script>
  var _paq = window._paq = window._paq || [];
  /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="https://amgithub.matomo.cloud/";
    _paq.push(['setTrackerUrl', u+'matomo.php']);
    _paq.push(['setSiteId', '1']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.async=true; g.src='//cdn.matomo.cloud/amgithub.matomo.cloud/matomo.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
<!-- End Matomo Code -->

