---
title: " "
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'research.html'))})
output:
  html_document:
    df_print: paged
    css: "style.css"
---

<center> <h1></h1> </center>

<div>
<div style="margin-bottom:20px;">
</div>


## Upcoming Invited Research Talks ##
  
- #### "The effect of access to mental healthcare on teen and adolescent pregnancy" ####
  
  - _November 18-20_, Southern Economic Association 93rd Annual Meeting 

## Dissertation Research ##

### _My vision_ ###

My primary research interests lie at the intersection of Public Economics and Applied Econometrics. I am particularly interested in studying how public policy in the US can better serve low-income and marginalized populations, especially how _interactions among public policies_ can directly or indirectly help facilitate human capital accumulation for such populations. I am especially interested in using microdata and rigorous research methods - robust quasi-experimental research designs - for this purpose. 

In my job market paper, I am using multiple quasi-experimental research designs to study not only whether the effects of exposure to a large-scale public program in childhood persist through adulthood, but also whether exposure to _multiple_ public programs, even from different domains (for example, a nutritional intervention early in life followed by an educational intervention later in childhood) can lead to “multiplier” effects - that is, when the combined positive effect of exposure to the two programs is larger than the sum of the effects of exposure to each of the two programs on their own. I believe that this newly gained knowledge could shift public policy thinking in the US in a new direction by encouraging policy makers to think about various public policies as elements of a single whole rather than disjoint pieces. By treating different public programs as elements of a single whole, policy makers could then work on making various public programs fit together better, in order to maximize human capital accumulation effects, not of any particular public program, but of the entire package of all relevant policies, i.e., public policy as a whole. 

In my other dissertation research, I am continuing this theme of whether human capital accumulation for low income populations can be supported by combining public policies that are currently seen by policy makers as disjoint unrelated pieces. In particular, I am using several quasi-experimental research designs to study whether combining expansion of access to mental healthcare for teenage and adolescent girls with expansion of access to family planning services can help them delay or avoid early pregnancy, thus facilitating human capital accumulation for young women.


#### 1. Long-term effects of the WIC program and policy multiplier effects of large-scale public programs ####

The Special Supplemental Nutrition Program for Women, Infants, and Children (WIC) has been in effect since the 1970s. In this project, I use two identification strategies to estimate the average causal intend-to-treat effects of the WIC program on a range of children’s longer-term outcomes such as health, human capital, and economic self-sufficiency in adulthood. The first identification strategy exploits variation across counties and over time from WIC geographical roll-out in the 1970s. For this purpose, I match adult outcomes of individuals in the American Community Survey and Decennial Census 2000 born in the 1970s with their place of birth information in the Social Security Administration's Numident File and then with the historical data on WIC geographical spread across counties. I find positive and statistically significant health effects for blacks in adulthood. Additionally, I find positive and statistically significant well-being effects for whites driven by improvements in health and economic self-sufficiency, in counties that had high teenage pregnancy rates prior to WIC introduction.My second identification strategy uses a regression discontinuity design, which I implement by developing county priority rankings for WIC funding in their state mirroring the approach by officials from the state of Texas, who developed such priority rankings for Texas counties in the early 1970s, as indicated by archival records. The use of this second identification strategy enables me to test the assumption common in this literature that the historical roll-out of WIC was exogenous or nearly exogenous. Finally, I study the dynamic complementarity effects of large-scale public programs and investments. In particular, I examine interaction effects between WIC and Head Start, between SNAP and Head Start, between SNAP and school quality reforms, between Medicaid and other programs, and some other program interactions. 

_A recent presentation of some of my findings is available here:_

<p style="text-align: left;">
<span class="my-text"><a href="https://github.com/annamalinovskaya/annamalinovskaya/blob/main/DIRC_Malinovskaya_slides_final.pdf?raw=true" style="color: #8B0000; text-decoration: underline;">Long Term Effects of the WIC Program - Data Intensive Research Conference, August 2023</a></span>
</p>

#### 2. The effect of access to mental healthcare on teen and adolescent pregnancy ####

There is a growing literature on the strong association between poor mental health during teenagehood and adolescence and early pregnancy, and although the association established in this literature is not causal, it nevertheless points to the possibility that poor mental health in teens and adolescents, if not addressed through access to appropriate mental healthcare, might lead to early pregnancy through an inconsistent use of contraception or risky sexual behaviors. In this project, I pursue several empirical approaches to analyze the effect of access to mental healthcare under Medicaid on teen and adolescent pregnancy incidence. In particular, in my analysis of adolescent pregnancy, I leverage a discrete break in Medicaid eligibility at age 19 and study the effect of losing access to mental healthcare services provided by Medicaid on adolescent girls’ chances of pregnancy in the short-term. By using detailed data on girls' mental health histories, I distinguish between the effect of losing access to mental healthcare from the effect of losing access to general healthcare and low-cost contraception. In my analysis of teen pregnancy, I use several instruments for the wait time a girl faces for starting mental health treatment under Medicaid and test the hypothesis that longer wait times for starting treatment lead to higher chances of teen pregnancy. Additionally, I use a regression discontinuity design to study the consequences of eliminating age limit for Medicaid coverage of emergency contraception when obtained over-the-counter in select states, overall and for a sub-population of young women with mental health histories. 

#### 3.1 COVID-driven technology adoption and US firm labor demand ####

This project has three objectives. The first objective is to provide more direct evidence than is currently available that technology adoption has a permanent upskilling effect, using granular firm-level data on technology adoption decisions and spending linked to the data on firm-level labor demand, with the identification strategy (instrumental variable) that addresses the endogeneity of firm technology adoption decisions and spending. For this purpose, I link rich Burning Glass Technologies data on millions of firm job postings to restricted firm-level Census Bureau data, and use firms' differential exposure to the COVID pandemic as an instrument for their technology spending. The second objective of this study is to examine in great detail the heterogeneity in the impacts of technology adoption on firm labor demand by type of technology. Understanding this heterogeneity might be crucial to understanding the potential impacts of _new_ technologies on the inequality among workers of different skill levels. Finally, the third objective is to provide first empirical evidence on new job task creation activity by firms. In particular, I use Natural Language Processing methods to identify, quantify, and characterize the distribution of, new job task creation activity by firms over the past 15 years. 

_A more detailed description of this project is available on the Russell Sage Foundation website <a href="https://www.russellsage.org/sites/default/files/sample_drg_proposals.pdf" style="color: #8B0000; text-decoration: underline;">here</a>._ 

#### 3.2 The COVID pandemic and new work ####

This project uses proprietary Burning Glass Technologies data on millions of job postings in the US over 2007-2022 to identify new work creation activity by firms following the COVID pandemic. Specifically, we take the approach similar to Autor et al. (2022) and identify, at a very granular level, new job titles that appeared during and immediately after the pandemic, with a particular focus on several industries, such as healthcare. We then characterize the geographical, industry, and occupational distribution of this new work creation activity. We also evaluate the skill content of new work, as well as its educational and experience requirements, to understand whether it is expected to affect higher or lower skill workers. Finally, we link job postings by employer over time to evaluate whether younger firms are more likely to engage in new work creation. This project is part of a larger study that links Burning Glass Technologies data with restricted firm-level Census Bureau data to estimate the effect of COVID-driven technology adoption on US firm labor demand.


</div>
<div style="margin-bottom:20px;">
</div>

<!-- Matomo -->
<script>
  var _paq = window._paq = window._paq || [];
  /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="https://amgithub.matomo.cloud/";
    _paq.push(['setTrackerUrl', u+'matomo.php']);
    _paq.push(['setSiteId', '1']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.async=true; g.src='//cdn.matomo.cloud/amgithub.matomo.cloud/matomo.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
<!-- End Matomo Code -->


